<?php
require_once __DIR__ . '/auth.php';
require_login();

if (!is_admin() && !is_analyst()) {
    http_response_code(403);
    die('Access denied. You do not have permission to export this report.');
}

require_once __DIR__ . '/db.php';

$autoloadPath = __DIR__ . '/../vendor/autoload.php';
if (!file_exists($autoloadPath)) {
    http_response_code(500);
    die('PDF export package is not installed. Run "composer install" in reporting.hknucsd-outreach.org first.');
}

require_once $autoloadPath;

use Dompdf\Dompdf;
use Dompdf\Options;

function event_count_for_export(string $json): int {
    $decoded = json_decode($json, true);
    if (!is_array($decoded)) {
        return 0;
    }

    return isset($decoded['events']) && is_array($decoded['events']) ? count($decoded['events']) : 0;
}

function pretty_json_for_export(string $json): string {
    $decoded = json_decode($json, true);
    if ($decoded === null) {
        return $json;
    }

    return json_encode($decoded, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
}

function trim_text_for_export(string $text, int $limit): string {
    if (function_exists('mb_strlen') && function_exists('mb_substr')) {
        if (mb_strlen($text) <= $limit) {
            return $text;
        }

        return mb_substr($text, 0, $limit) . "\n... (truncated)";
    }

    if (strlen($text) <= $limit) {
        return $text;
    }

    return substr($text, 0, $limit) . "\n... (truncated)";
}

function cleanup_old_exports(string $exportsDir, int $maxAgeDays = 7): void {
  if (!is_dir($exportsDir)) {
    return;
  }

  $threshold = time() - ($maxAgeDays * 86400);
  $pattern = $exportsDir . '/report-export-*.pdf';

  foreach (glob($pattern) ?: [] as $filePath) {
    if (!is_file($filePath)) {
      continue;
    }

    $modifiedAt = filemtime($filePath);
    if ($modifiedAt !== false && $modifiedAt < $threshold) {
      @unlink($filePath);
    }
  }
}

$stmt = $pdo->query("
    SELECT id, received_at, sid, page, sent_at, payload
    FROM beacons_raw
    ORDER BY received_at DESC
    LIMIT 100
");
$rows = $stmt->fetchAll(PDO::FETCH_ASSOC);

$generatedAt = date('Y-m-d H:i:s');
$generatedBy = $_SESSION['display_name'] ?? $_SESSION['username'];

$html = '<!doctype html>';
$html .= '<html><head><meta charset="UTF-8"><style>';
$html .= 'body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #111827; }';
$html .= 'h1 { margin: 0 0 8px; font-size: 22px; }';
$html .= '.meta { margin-bottom: 14px; color: #374151; }';
$html .= 'table { width: 100%; border-collapse: collapse; table-layout: fixed; }';
$html .= 'th, td { border: 1px solid #d1d5db; padding: 8px; vertical-align: top; word-wrap: break-word; }';
$html .= 'th { background: #f3f4f6; text-align: left; }';
$html .= '.mono { font-family: DejaVu Sans Mono, monospace; font-size: 10px; }';
$html .= '.small { font-size: 10px; color: #4b5563; }';
$html .= '</style></head><body>';
$html .= '<h1>Collected Beacon Data Export</h1>';
$html .= '<div class="meta">Generated at: ' . htmlspecialchars($generatedAt) . ' | Generated by: ' . htmlspecialchars($generatedBy) . ' | Records: ' . count($rows) . '</div>';
$html .= '<table><thead><tr>';
$html .= '<th style="width:4%">ID</th>';
$html .= '<th style="width:11%">Received</th>';
$html .= '<th style="width:18%">Session ID</th>';
$html .= '<th style="width:14%">Page</th>';
$html .= '<th style="width:11%">Sent At</th>';
$html .= '<th style="width:7%">Events</th>';
$html .= '<th style="width:35%">Payload Preview</th>';
$html .= '</tr></thead><tbody>';

if (empty($rows)) {
    $html .= '<tr><td colspan="7">No beacon data found.</td></tr>';
} else {
    foreach ($rows as $row) {
        $payloadPreview = pretty_json_for_export((string)$row['payload']);
        $payloadPreview = trim_text_for_export($payloadPreview, 1400);

        $html .= '<tr>';
        $html .= '<td>' . htmlspecialchars((string)$row['id']) . '</td>';
        $html .= '<td>' . htmlspecialchars((string)$row['received_at']) . '</td>';
        $html .= '<td class="mono">' . htmlspecialchars((string)$row['sid']) . '</td>';
        $html .= '<td>' . htmlspecialchars((string)($row['page'] ?? '')) . '</td>';
        $html .= '<td>' . htmlspecialchars((string)($row['sent_at'] ?? '')) . '</td>';
        $html .= '<td>' . event_count_for_export((string)$row['payload']) . '</td>';
        $html .= '<td class="mono">' . nl2br(htmlspecialchars($payloadPreview)) . '</td>';
        $html .= '</tr>';
    }
}

$html .= '</tbody></table>';
$html .= '<p class="small">This export is generated from the latest 100 records.</p>';
$html .= '</body></html>';

$options = new Options();
$options->set('isRemoteEnabled', false);
$options->set('defaultFont', 'DejaVu Sans');

$dompdf = new Dompdf($options);
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'landscape');
$dompdf->render();

$pdfBinary = $dompdf->output();

$exportsDir = __DIR__ . '/exports';
if (!is_dir($exportsDir) && !mkdir($exportsDir, 0775, true) && !is_dir($exportsDir)) {
    http_response_code(500);
    die('Failed to create export directory.');
}

cleanup_old_exports($exportsDir, 7);

$filename = 'report-export-' . date('Ymd-His') . '-' . bin2hex(random_bytes(4)) . '.pdf';
$filePath = $exportsDir . '/' . $filename;

if (file_put_contents($filePath, $pdfBinary) === false) {
    http_response_code(500);
    die('Failed to save exported PDF.');
}

$scheme = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
$host = $_SERVER['HTTP_HOST'] ?? 'localhost';
$publicUrl = $scheme . '://' . $host . '/exports/' . rawurlencode($filename);
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Report Export Complete</title>
  <style>
    :root {
      --bg: #f6f8fb;
      --card: #ffffff;
      --text: #1f2937;
      --muted: #6b7280;
      --border: #e5e7eb;
      --accent: #2563eb;
    }

    * { box-sizing: border-box; }

    body {
      margin: 0;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      background: var(--bg);
      color: var(--text);
    }

    .container {
      max-width: 900px;
      margin: 40px auto;
      padding: 0 20px;
    }

    .card {
      background: var(--card);
      border: 1px solid var(--border);
      border-radius: 16px;
      box-shadow: 0 8px 24px rgba(0,0,0,0.05);
      padding: 24px;
    }

    h1 {
      margin: 0 0 8px;
      font-size: 1.6rem;
    }

    p { color: var(--muted); }

    .url-box {
      margin: 16px 0;
      padding: 12px;
      border: 1px solid var(--border);
      border-radius: 8px;
      background: #f9fafb;
      word-break: break-all;
      font-family: "Courier New", monospace;
      color: #111827;
    }

    .actions {
      margin-top: 20px;
      display: flex;
      gap: 12px;
      flex-wrap: wrap;
    }

    .btn {
      text-decoration: none;
      display: inline-block;
      padding: 10px 16px;
      border-radius: 8px;
      font-weight: 600;
      font-size: 0.95rem;
    }

    .btn.primary {
      background: var(--accent);
      color: white;
    }

    .btn.secondary {
      background: #e5e7eb;
      color: #111827;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="card">
      <h1>PDF Export Created</h1>
      <p>Your report has been exported and saved to a public URL.</p>
      <div class="url-box"><?= htmlspecialchars($publicUrl) ?></div>
      <div class="actions">
        <a class="btn primary" href="<?= htmlspecialchars('/exports/' . $filename) ?>" target="_blank" rel="noopener">Open PDF</a>
        <a class="btn secondary" href="/report.php">Back to Report</a>
      </div>
    </div>
  </div>
</body>
</html>
